name: deen_lab
description: "An adaptive Islamic platform for personalized tools and worship assistance."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_compass: ^0.8.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.13.1


  widget_git_release_checker:
    git:
      url: https://github.com/Holy-Warrior/widget_git_release_checker.git

  silence_of_salah_engine:
    git:
      url: https://github.com/Holy-Warrior/silence_of_salah_engine.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "resources/deenlab_logo.png"

flutter:

  uses-material-design: true
